version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: BlinKay 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Pasword10! #testPassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: blinkaytest-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__PostgreSQLConnection=Host=postgres;Database=BlinKay;Username=postgres;Password=Pasword10!
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  postgres_data: